### PR TITLE
support robthree/twofactorauth v2

### PR DESCRIPTION
**Pull request by LordSimal**
See https://github.com/CakeDC/auth/pull/77

### CODE REVIEW

**Comment by LordSimal** [comment]
You want me to fix the CS Problems in this PR as well or should this be part of another PR?

**Comment by rochamarcelo** [comment]
What are the steps to upgrade an application using this?

**Comment by LordSimal** [comment]
This currently works for me without a problem on CakePHP 4.4 with PHP 8.1 (since its a requirement of that new package version). All I had to add/adjust in my `config/users.php` was 
```
    'OneTimePasswordAuthenticator' => [
        'algorithm' => \RobThree\Auth\Algorithm::Sha1,
    ]
```
and of course upgrade the package.

**Comment by rochamarcelo** [comment]
Thank You.

**Pull request merged**
