### PR TITLE
Superuser addOptions

### PR DESCRIPTION
**Pull request by digitalfotografen**
addUser and addSuperuser where repeats. Moved most of the logic to a
new method called _createUser

Sorry for one extra commit and pull request on this ;)

### CODE REVIEW

**Comment by steinkel** [comment]
Please fix phpcs

**Comment by digitalfotografen** [comment]
I withdraw this pull request. I am not good enough on writing tests to fix the coverage problems. Decided to keep a working code with some repetitions instead of breaking tests.

**Comment by steinkel** [comment]
Hey @digitalfotografen your PR looked nice, the only thing missing was fixing minor PHPCS issues, I can help you to fix that to pass the build. You just need to do this:

* Install phpcs following this howto > https://github.com/cakephp/cakephp-codesniffer#installation
I usually install it globally, not project based
Then run it and check the errors found in phpcs like
    phpcs --standard=CakePHP /path/to/code
You can install phpcs in your favourite IDE too and let it run auto on file changes...
If you have issues with this I can fix phpcs for you and merge.

Thanks, and sorry for the late answer I was off a couple days...

**Comment by digitalfotografen** [comment]
Hi steinkel,
thanks for the information about PHPCS. I haven't used that locally before. I learned something new.

There is one warning left on the UsersShellTest - but that is an old one reminding to extend the tests.

/Ulrik alias digitalfotografen

**Comment by steinkel** [comment]
well done!

May the phpcs be with you, always

**Pull request merged**
