### PR TITLE
Using `UsersUrl::actionUrl()` for redirects

### PR DESCRIPTION
**Pull request by groovenectar**
This seems to be the right pattern for the login action. After verifying email, it wasn't redirecting to the default `/login` URL, instead to `/users/login`

I tried using the Change Password link as well... Using `UsersUrl::actionUrl()`, it seems to work fine. It redirects to `/users/change-password` and the flow seems operational.

Hopefully this is on the right track

### CODE REVIEW

**Comment by rochamarcelo** [comment]
Failing tests

**Comment by groovenectar** [comment]
It looks like the develop branch tests are still broken:
https://travis-ci.org/CakeDC/users/builds/605199179

**Comment by rochamarcelo** [comment]
Check https://travis-ci.org/CakeDC/users/jobs/605199180, it will show the errors.

**Comment by rochamarcelo** [comment]
By the way could you send pull request to 9.next?

**Comment by groovenectar** [comment]
Okay I changed the branch... I've still been working with the `develop` branch since I may want to stick with Cake3 LTS for a while (haven't decided yet)

But I think that the failing tests are due to problems with the build system in this branch. This happened to a couple other PRs as well in this branch

**Comment by rochamarcelo** [comment]
Which build system issue are you referring to? It seems to be running normally. You can also run the tests locally

**Comment by groovenectar** [comment]
@rochamarcelo Are all of these errors not related to the database connection?

image

**Comment by rochamarcelo** [comment]
It says  that failed for all php versions, check the log (click on each item) to see the errors (phpunit). You can run phpunit locally.

**Comment by groovenectar** [comment]
@rochamarcelo The tests themselves are actually problematic in this case:

https://github.com/CakeDC/users/blob/master/tests/TestCase/Controller/Traits/RegisterTraitTest.php#L145

They don't support customizing the redirects via the config... I'm going to have to update the tests in order to get the PR passing them

**Comment by rochamarcelo** [comment]
You just have to include 'plugin', 'prefix' and 'controller' keys for expected values.

Also, the branch has **_conflicting files_**.

**Comment by rochamarcelo** [comment]
Issue fixed at https://github.com/CakeDC/users/pull/858. Thank you.

**Pull request closed without merging**
