### PR TITLE
Add changes of 11.2.0 release

### PR DESCRIPTION
**Pull request by ravage84**

### CODE REVIEW

**Comment by rochamarcelo** [comment]
Thank you @ravage84 . Could you send a pull request to 11.next-cake4 branch.

**Comment by ravage84** [comment]
@rochamarcelo I just switched the target. It seems to take a few additional changes with it. But they look fine, anyway.

**Comment by rochamarcelo** [comment]
I see that CHANGELOG.md is conflicting now.

**Comment by ravage84** [comment]
@rochamarcelo did a rebase and some minor improvements.

**Comment by rochamarcelo** [comment]
Thanks @ravage84

**Pull request merged**
