### PR TITLE
Replace deprecated methods for CakePHP 3.6

### PR DESCRIPTION
**Pull request by jtraulle**
All deprecated methods/properties has been replaced by the new ones.
Test has been modified accordingly.

### CODE REVIEW

**Comment by steinkel** [comment]
Impressive!
We'll take a look ASAP, thank you!!

**Comment by jtraulle** [comment]
All **Friends Of Cake** _cake-36_ branches has been merged :tada: 
Have you had a chance to get a quick look at this MR @steinkel ? Last thing to be tagged/released before I can upgrade my app to 3.6 :wink: 
No pressure however :kissing_heart:

**Comment by saeideng** [comment]
you should update your branch before creating PR
or for now, re-base on develop

**Comment by medero** [comment]
Nice work! Also looking to use in a 3.6 upgrade so can't wait!

**Pull request merged**
