### PR TITLE
When saving, setting the save format of datetime fields to not use th…

### PR DESCRIPTION
**Pull request by zsfoto**
When saving, setting the save format of datetime fields to not use the localized format.

### CODE REVIEW

**Comment by steinkel** [comment]
The proposed change would affect the FrozenTime formatting globally. Is there any specific save operation that should be modified?

I understand you are proposing this change to fix a specific issue on your side, instead of a fix, could you provide a use case or unit test to reproduce the issue locally and fix it in the save operation instead?

Thanks,

**Comment by zsfoto** [comment]
Hi!

The problem is during saving, when the date and time string is not transferred to the SQL server in the X-m-d H:i:s format.
Below is an error message. If I set it to hu_HU, it would be transferred according to the Hungarian format and not uniformly as it should be ("Y-m-d H:i:s" would be appropriate)

SQLSTATE[22007]: Invalid datetime format: 1292 Incorrect datetime value: '9/15/23, 7:07 AM' for column `notes`.`users`.`last_login` at row 1

What is passed to the SQL server is the format that can also be read in the error message: "9/15/23, 7:07 AM"

**Comment by zsfoto** [comment]
When I fixed this, it was resolved.

**Comment by zsfoto** [comment]
Yes, the problem is when it comes up.
For example, when I want to log in or register as a new user.
That is, operations that would save the new value in datetime format.

**Comment by steinkel** [comment]
Got it, we'll provide a patch to ensure the time is NOT formatted using the default formatter, but enforce the formatting instead.

**Comment by steinkel** [comment]
I'll open a ticket for this issue thanks

**Pull request closed without merging**
