### PR TITLE
Add postLink method in AuthLinkHelper and add test on postlink with a…

### PR DESCRIPTION
**Pull request by maxime-vacossin**
Add postLink method in AuthLinkHelper and add test on postlink with and without logged users

### CODE REVIEW

**Comment by rochamarcelo** [comment]
@maxime-vacossin could send this to 9.next branch?

**Comment by maxime-vacossin** [comment]
@rochamarcelo Done !

I see the new update in the readme file for the OUTDATED branch, sorry, I follow  the contribution guidlines : https://www.cakedc.com/contribution-guidelines

> Create a new branch from develop for a feature, or from master if a bug fix. 


This branch has conflict, i'll fix asap ! (tomorow 😃 )

**Comment by rochamarcelo** [comment]
Thank you @maxime-vacossin . The 9.next branch is for CakePHP 4 and new features.

**Comment by maxime-vacossin** [comment]
Can't test locally, waiting https://github.com/CakeDC/users/pull/857 for rebase first =)

**Comment by rochamarcelo** [comment]
Hi @maxime-vacossin ,

I see this error https://travis-ci.org/CakeDC/users/jobs/646440335?utm_medium=notification&utm_source=github_status

Are you able to fix it?

**Comment by rochamarcelo** [comment]
Also the warning in ReadMe file is not needed could you please remove it from you branch?

**Comment by rochamarcelo** [comment]
Thank you @maxime-vacossin

**Pull request merged**
