### PR TITLE
Enable MiddlewareQueueLoader Extension

### PR DESCRIPTION
**Pull request by T0mats0**
See issue #919 

Created 2 objects to replace functions that were on the Plugin class: AuthorizationServiceProvider and AuthenticationServiceProvider. Both of these class implement the respective interfaces previously on the Plugin class. Both classes are now passed MiddlewareQueueLoader and type hints that were to the concretion "Plugin" are now the abstraction interfaces.

While the interfaces have changed on the MiddlewareQueueLoader, much of the code in execution remains the same.  Most of what's here was just moving things around.

### CODE REVIEW

**Comment by rochamarcelo** [comment]
Thank you @T0mats0 . I see some minor issues at https://travis-ci.org/github/CakeDC/users/builds/742824627 are you able to fix it?

**Comment by T0mats0** [comment]
This error appears to be not in my PR in 9.next in general.

Screen Shot 2020-11-12 at 7 11 18 AM

Otherwise it looks like all other checks are passing. Travis CI takes so long to run tests and checks that run in just a few seconds in my local -- really suprised.

**Review by steinkel — CHANGES_REQUESTED** [review]
It looks good to me but these changes would make sense in the 10.next branch.

**Comment by T0mats0** [comment]
Thank you. Sounds great. I'll update the pointer when there is a branch.

**Comment by steinkel** [comment]
Branch 10.next-cake4 created

**Pull request merged**
