### PR TITLE
Solves Issue #431 - Allow custom role on user registration

### PR DESCRIPTION
**Pull request by digitalfotografen**
* Added option --role in console users addUser too assign role
* Added textfield role in add.ctp and edit.ctp
* Added display of role in view.ctp
* Updated test UserShellTest testAddUser and testAddUserWithNoParams to
check for role. Since role is a protected field this had to be handled
slightly awkward

### CODE REVIEW

**Comment by digitalfotografen** [comment]
After a nights sleep I realized that adding the role field to the add.ctp and edit.ctp templates was a bad idea, thats the reason for the second commit. But having this option in the console saves time when setting up systems and users.

**Comment by steinkel** [comment]
@digitalfotografen this is looking great, please fix https://travis-ci.org/CakeDC/users/jobs/199884685#L259 phpcs minor issue, I'll take a look at the failing tests and merge it, thanks!

**Comment by steinkel** [comment]
tests fixed in develop, feel free to rebase this branch please. Thanks

**Comment by steinkel** [comment]
Thanks!

**Pull request merged**
