### PR TITLE
change validation criteria for the TOS field to only accept "1"

### PR DESCRIPTION
**Pull request by mferak**
References #328

### CODE REVIEW

**Comment by mferak** [comment]
I'm sorry, I don't know what I'm doing wrong. Never done this before.

**Comment by steinkel** [comment]
hey @mferak thank you for sending the pull request. The issues from travis are not related with your code. The only issue is coveralls, as you are adding new code, if you have the time you should also commit some unit tests to cover the new validation. Please check the https://github.com/CakeDC/users/blob/develop/tests/TestCase/Model/Behavior/RegisterBehaviorTest.php file and add the tests to check the new conditions. Thanks,

**Comment by steinkel** [comment]
@mferak any updates here? how could we help you?

**Comment by mferak** [comment]
Sorry, tests-wise I'm really a noob, and I didn't get a chance to look into how to make/modify unit tests yet. (Perhaps it's self-explanatory and I'm just afraid of something I haven't done before! Ha.)

**Comment by mtancoigne** [comment]
It seems Travis fails on PHPUnit deprecated methods for php 5.6. @meferak, you should update your fork to pull the last updates from here and see if it still fail. The tests are passing on a fresh PR, i think this has been fixed.

**Comment by steinkel** [comment]
Please update this PR to be able to close it

**Comment by steinkel** [comment]
closed as obsolete

**Pull request closed without merging**
